STRINGS_DE = {
    "main.title": "Soplos Systemdienste",
    "tab.services": "Dienste",
    "tab.logs": "Protokolle",
    "table.name": "Name",
    "table.loaded": "Geladen",
    "table.active": "Aktiv",
    "table.sub": "Substatus",
    "table.description": "Beschreibung",
    "btn.start": "Starten",
    "btn.stop": "Stoppen",
    "btn.restart": "Neustarten",
    "btn.enable": "Aktivieren",
    "btn.disable": "Deaktivieren",
    "btn.refresh": "Aktualisieren",
    "details.no_selection": "Wahlen Sie einen Dienst aus, um Details anzuzeigen",
    "details.status": "Status",
    "details.description": "Beschreibung",
    "logs.select_service": "Wahlen Sie einen Dienst im Reiter Dienste aus, um seine Protokolle zu sehen",
    "logs.no_logs": "Keine Protokolle fur diesen Dienst verfugbar",
    "status.loading": "Dienste werden geladen...",
    "status.ready": "Bereit",
    "status.error": "Fehler beim Laden der Dienste",
    "confirm.title": "Bestatigen",
    "confirm.start": "Dienst {name} starten?",
    "confirm.stop": "Dienst {name} stoppen?",
    "confirm.restart": "Dienst {name} neu starten?",
    "confirm.enable": "Dienst {name} aktivieren?",
    "confirm.disable": "Dienst {name} deaktivieren?",
    "about.comments": "Grafische GTK3-Verwaltungsoberflache fur systemd-Dienste unter Soplos Linux.",
}
