STRINGS_DE = {
    "main.title": "Soplos Systemdienste",
    "tab.services": "Dienste",
    "tab.logs": "Protokolle",
    "table.name": "Name",
    "table.loaded": "Geladen",
    "table.active": "Aktiv",
    "table.sub": "Substatus",
    "table.description": "Beschreibung",
    "btn.start": "Starten",
    "btn.stop": "Stoppen",
    "btn.restart": "Neustarten",
    "btn.enable": "Aktivieren",
    "btn.disable": "Deaktivieren",
    "btn.refresh": "Aktualisieren",
    "details.no_selection": "Wahlen Sie einen Dienst aus, um Details anzuzeigen",
    "details.status": "Status",
    "details.description": "Beschreibung",
    "logs.select_service": "Wahlen Sie einen Dienst im Reiter Dienste aus, um seine Protokolle zu sehen",
    "logs.no_logs": "Keine Protokolle fur diesen Dienst verfugbar",
    "status.loading": "Dienste werden geladen...",
    "status.ready": "Bereit",
    "status.error": "Fehler beim Laden der Dienste",
    "confirm.title": "Bestatigen",
    "confirm.start": "Dienst {name} starten?",
    "confirm.stop": "Dienst {name} stoppen?",
    "confirm.restart": "Dienst {name} neu starten?",
    "confirm.enable": "Dienst {name} aktivieren?",
    "confirm.disable": "Dienst {name} deaktivieren?",
    "about.comments": "Grafische GTK3-Verwaltungsoberflache fur systemd-Dienste unter Soplos Linux.",
    "tab.optimization": "Optimierung",
    "opt.column.service": "Dienst",
    "opt.column.category": "Kategorie",
    "opt.column.resource": "Ressource",
    "opt.column.reason": "Grund",
    "opt.column.risk": "Risiko",
    "opt.btn.scan": "Scannen",
    "opt.btn.apply": "Auswahl anwenden",
    "opt.btn.select_all": "Alles auswahlen",
    "opt.status.scanning": "System wird gescannt...",
    "opt.status.none_found": "Keine Vorschlage gefunden",
    "opt.status.applying": "Anderungen werden angewendet...",
    "opt.category.hardware": "Hardware nicht vorhanden",
    "opt.category.redundant": "Redundanter Stack",
    "opt.category.orphan": "Verwaistes Paket",
    "opt.resource.ram": "RAM",
    "opt.resource.boot": "Startzeit",
    "opt.resource.power": "Energie",
    "opt.risk.low": "Niedrig",
    "opt.risk.medium": "Mittel",
    "opt.reason.no_vm": "Keine virtuelle Maschine erkannt",
    "opt.reason.no_bluetooth": "Kein Bluetooth-Adapter erkannt",
    "opt.reason.no_wifi": "Kein WLAN-Adapter erkannt",
    "opt.reason.audio_redundant": "PipeWire ist aktiv; PulseAudio ist redundant",
    "opt.reason.orphan_pkg": "Das installierende Paket {pkg} ist nicht mehr vorhanden",
    "opt.confirm.header": "Folgende Anderungen werden angewendet:",
    "opt.confirm.summary_disable": "Deaktivieren: {count}",
    "opt.confirm.summary_enable": "Aktivieren: {count}",
    "opt.confirm.summary_remove": "Verwaisten Link entfernen: {count}",
    "opt.resource.disk": "Festplatte",
    "opt.category.maintenance": "Empfohlene Wartung",
    "opt.category.boot_block": "Blockiert den Start",
    "opt.reason.fstrim_missing": "SSD/NVMe erkannt, aber regelmasiges TRIM ist nicht aktiviert",
    "opt.reason.netm_wait_online": "Verzogert den Start, bis das Netzwerk bereit ist",
    "opt.resource.cleanup": "Bereinigung",
    "opt.reason.orphan_symlink": "Defekter Aktivierungslink ({paths}): das Paket, das ihn erstellt hat, ist nicht mehr installiert",
}
