STRINGS_EN = {
    "main.title": "Soplos System Services",
    "tab.services": "Services",
    "tab.logs": "Logs",
    "table.name": "Name",
    "table.loaded": "Loaded",
    "table.active": "Active",
    "table.sub": "Sub",
    "table.description": "Description",
    "btn.start": "Start",
    "btn.stop": "Stop",
    "btn.restart": "Restart",
    "btn.enable": "Enable",
    "btn.disable": "Disable",
    "btn.refresh": "Refresh",
    "details.no_selection": "Select a service to view details",
    "details.status": "Status",
    "details.description": "Description",
    "logs.select_service": "Select a service in the Services tab to view its logs",
    "logs.no_logs": "No logs available for this service",
    "status.loading": "Loading services...",
    "status.ready": "Ready",
    "status.error": "Error loading services",
    "confirm.title": "Confirm",
    "confirm.start": "Start service {name}?",
    "confirm.stop": "Stop service {name}?",
    "confirm.restart": "Restart service {name}?",
    "confirm.enable": "Enable service {name}?",
    "confirm.disable": "Disable service {name}?",
    "about.comments": "GTK3 graphical manager for systemd services on Soplos Linux.",
}
