STRINGS_EN = {
    "main.title": "Soplos System Services",
    "tab.services": "Services",
    "tab.logs": "Logs",
    "table.name": "Name",
    "table.loaded": "Loaded",
    "table.active": "Active",
    "table.sub": "Sub",
    "table.description": "Description",
    "btn.start": "Start",
    "btn.stop": "Stop",
    "btn.restart": "Restart",
    "btn.enable": "Enable",
    "btn.disable": "Disable",
    "btn.refresh": "Refresh",
    "details.no_selection": "Select a service to view details",
    "details.status": "Status",
    "details.description": "Description",
    "logs.select_service": "Select a service in the Services tab to view its logs",
    "logs.no_logs": "No logs available for this service",
    "status.loading": "Loading services...",
    "status.ready": "Ready",
    "status.error": "Error loading services",
    "confirm.title": "Confirm",
    "confirm.start": "Start service {name}?",
    "confirm.stop": "Stop service {name}?",
    "confirm.restart": "Restart service {name}?",
    "confirm.enable": "Enable service {name}?",
    "confirm.disable": "Disable service {name}?",
    "about.comments": "GTK3 graphical manager for systemd services on Soplos Linux.",
    "tab.optimization": "Optimization",
    "opt.column.service": "Service",
    "opt.column.category": "Category",
    "opt.column.resource": "Resource",
    "opt.column.reason": "Reason",
    "opt.column.risk": "Risk",
    "opt.btn.scan": "Scan",
    "opt.btn.apply": "Apply selected",
    "opt.btn.select_all": "Select all",
    "opt.status.scanning": "Scanning system...",
    "opt.status.none_found": "No suggestions found",
    "opt.status.applying": "Applying changes...",
    "opt.category.hardware": "Hardware not present",
    "opt.category.redundant": "Redundant stack",
    "opt.category.orphan": "Orphaned package",
    "opt.resource.ram": "RAM",
    "opt.resource.boot": "Boot time",
    "opt.resource.power": "Power",
    "opt.risk.low": "Low",
    "opt.risk.medium": "Medium",
    "opt.reason.no_vm": "No virtual machine detected",
    "opt.reason.no_bluetooth": "No Bluetooth adapter detected",
    "opt.reason.no_wifi": "No Wi-Fi adapter detected",
    "opt.reason.audio_redundant": "PipeWire is active; PulseAudio is redundant",
    "opt.reason.orphan_pkg": "Owning package {pkg} is no longer installed",
    "opt.confirm.header": "The following changes will be applied:",
    "opt.confirm.summary_disable": "Disable: {count}",
    "opt.confirm.summary_enable": "Enable: {count}",
    "opt.confirm.summary_remove": "Remove orphaned link: {count}",
    "opt.resource.disk": "Disk",
    "opt.category.maintenance": "Recommended maintenance",
    "opt.category.boot_block": "Blocks boot",
    "opt.reason.fstrim_missing": "SSD/NVMe detected but periodic TRIM is not enabled",
    "opt.reason.netm_wait_online": "Delays boot waiting for the network to be ready",
    "opt.resource.cleanup": "Cleanup",
    "opt.reason.orphan_symlink": "Broken enablement link ({paths}): the package that created it is no longer installed",
}
