STRINGS_ES = {
    "main.title": "Servicios del sistema Soplos",
    "tab.services": "Servicios",
    "tab.logs": "Registros",
    "table.name": "Nombre",
    "table.loaded": "Cargado",
    "table.active": "Activo",
    "table.sub": "Subestado",
    "table.description": "Descripcion",
    "btn.start": "Iniciar",
    "btn.stop": "Parar",
    "btn.restart": "Reiniciar",
    "btn.enable": "Activar",
    "btn.disable": "Desactivar",
    "btn.refresh": "Actualizar",
    "details.no_selection": "Selecciona un servicio para ver los detalles",
    "details.status": "Estado",
    "details.description": "Descripcion",
    "logs.select_service": "Selecciona un servicio en la pestana Servicios para ver sus registros",
    "logs.no_logs": "No hay registros disponibles para este servicio",
    "status.loading": "Cargando servicios...",
    "status.ready": "Listo",
    "status.error": "Error al cargar los servicios",
    "confirm.title": "Confirmar",
    "confirm.start": "Iniciar el servicio {name}?",
    "confirm.stop": "Parar el servicio {name}?",
    "confirm.restart": "Reiniciar el servicio {name}?",
    "confirm.enable": "Activar el servicio {name}?",
    "confirm.disable": "Desactivar el servicio {name}?",
    "about.comments": "Gestor grafico GTK3 para servicios systemd en Soplos Linux.",
    "tab.optimization": "Optimizacion",
    "opt.column.service": "Servicio",
    "opt.column.category": "Categoria",
    "opt.column.resource": "Recurso",
    "opt.column.reason": "Motivo",
    "opt.column.risk": "Riesgo",
    "opt.btn.scan": "Escanear",
    "opt.btn.apply": "Aplicar seleccionados",
    "opt.btn.select_all": "Seleccionar todo",
    "opt.status.scanning": "Analizando el sistema...",
    "opt.status.none_found": "No se han encontrado sugerencias",
    "opt.status.applying": "Aplicando cambios...",
    "opt.category.hardware": "Hardware no presente",
    "opt.category.redundant": "Stack redundante",
    "opt.category.orphan": "Paquete huerfano",
    "opt.resource.ram": "RAM",
    "opt.resource.boot": "Arranque",
    "opt.resource.power": "Energia",
    "opt.risk.low": "Bajo",
    "opt.risk.medium": "Medio",
    "opt.reason.no_vm": "No se detecta maquina virtual",
    "opt.reason.no_bluetooth": "No se detecta adaptador Bluetooth",
    "opt.reason.no_wifi": "No se detecta adaptador WiFi",
    "opt.reason.audio_redundant": "PipeWire esta activo; PulseAudio es redundante",
    "opt.reason.orphan_pkg": "El paquete {pkg} que lo instalo ya no esta presente",
    "opt.confirm.header": "Se van a aplicar los siguientes cambios:",
    "opt.confirm.summary_disable": "Deshabilitar: {count}",
    "opt.confirm.summary_enable": "Activar: {count}",
    "opt.confirm.summary_remove": "Eliminar enlace huerfano: {count}",
    "opt.resource.disk": "Disco",
    "opt.category.maintenance": "Mantenimiento recomendado",
    "opt.category.boot_block": "Bloquea el arranque",
    "opt.reason.fstrim_missing": "SSD/NVMe detectado pero el TRIM periodico no esta habilitado",
    "opt.reason.netm_wait_online": "Retrasa el arranque esperando a que la red este lista",
    "opt.resource.cleanup": "Limpieza",
    "opt.reason.orphan_symlink": "Enlace de activacion roto ({paths}): el paquete que lo creo ya no esta instalado",
}
