STRINGS_ES = {
    "main.title": "Servicios del sistema Soplos",
    "tab.services": "Servicios",
    "tab.logs": "Registros",
    "table.name": "Nombre",
    "table.loaded": "Cargado",
    "table.active": "Activo",
    "table.sub": "Subestado",
    "table.description": "Descripcion",
    "btn.start": "Iniciar",
    "btn.stop": "Parar",
    "btn.restart": "Reiniciar",
    "btn.enable": "Activar",
    "btn.disable": "Desactivar",
    "btn.refresh": "Actualizar",
    "details.no_selection": "Selecciona un servicio para ver los detalles",
    "details.status": "Estado",
    "details.description": "Descripcion",
    "logs.select_service": "Selecciona un servicio en la pestana Servicios para ver sus registros",
    "logs.no_logs": "No hay registros disponibles para este servicio",
    "status.loading": "Cargando servicios...",
    "status.ready": "Listo",
    "status.error": "Error al cargar los servicios",
    "confirm.title": "Confirmar",
    "confirm.start": "Iniciar el servicio {name}?",
    "confirm.stop": "Parar el servicio {name}?",
    "confirm.restart": "Reiniciar el servicio {name}?",
    "confirm.enable": "Activar el servicio {name}?",
    "confirm.disable": "Desactivar el servicio {name}?",
    "about.comments": "Gestor grafico GTK3 para servicios systemd en Soplos Linux.",
}
