STRINGS_FR = {
    "main.title": "Services systeme Soplos",
    "tab.services": "Services",
    "tab.logs": "Journaux",
    "table.name": "Nom",
    "table.loaded": "Charge",
    "table.active": "Actif",
    "table.sub": "Sous-etat",
    "table.description": "Description",
    "btn.start": "Demarrer",
    "btn.stop": "Arreter",
    "btn.restart": "Redemarrer",
    "btn.enable": "Activer",
    "btn.disable": "Desactiver",
    "btn.refresh": "Actualiser",
    "details.no_selection": "Selectionnez un service pour voir les details",
    "details.status": "Etat",
    "details.description": "Description",
    "logs.select_service": "Selectionnez un service dans l'onglet Services pour voir ses journaux",
    "logs.no_logs": "Aucun journal disponible pour ce service",
    "status.loading": "Chargement des services...",
    "status.ready": "Pret",
    "status.error": "Erreur lors du chargement des services",
    "confirm.title": "Confirmer",
    "confirm.start": "Demarrer le service {name} ?",
    "confirm.stop": "Arreter le service {name} ?",
    "confirm.restart": "Redemarrer le service {name} ?",
    "confirm.enable": "Activer le service {name} ?",
    "confirm.disable": "Desactiver le service {name} ?",
    "about.comments": "Gestionnaire graphique GTK3 pour les services systemd sous Soplos Linux.",
    "tab.optimization": "Optimisation",
    "opt.column.service": "Service",
    "opt.column.category": "Categorie",
    "opt.column.resource": "Ressource",
    "opt.column.reason": "Motif",
    "opt.column.risk": "Risque",
    "opt.btn.scan": "Analyser",
    "opt.btn.apply": "Appliquer la selection",
    "opt.btn.select_all": "Tout selectionner",
    "opt.status.scanning": "Analyse du systeme...",
    "opt.status.none_found": "Aucune suggestion trouvee",
    "opt.status.applying": "Application des changements...",
    "opt.category.hardware": "Materiel absent",
    "opt.category.redundant": "Pile redondante",
    "opt.category.orphan": "Paquet orphelin",
    "opt.resource.ram": "RAM",
    "opt.resource.boot": "Demarrage",
    "opt.resource.power": "Energie",
    "opt.risk.low": "Faible",
    "opt.risk.medium": "Moyen",
    "opt.reason.no_vm": "Aucune machine virtuelle detectee",
    "opt.reason.no_bluetooth": "Aucun adaptateur Bluetooth detecte",
    "opt.reason.no_wifi": "Aucun adaptateur Wi-Fi detecte",
    "opt.reason.audio_redundant": "PipeWire est actif ; PulseAudio est redondant",
    "opt.reason.orphan_pkg": "Le paquet {pkg} qui l'a installe n'est plus present",
    "opt.confirm.header": "Les changements suivants vont etre appliques :",
    "opt.confirm.summary_disable": "Desactiver : {count}",
    "opt.confirm.summary_enable": "Activer : {count}",
    "opt.confirm.summary_remove": "Supprimer le lien orphelin : {count}",
    "opt.resource.disk": "Disque",
    "opt.category.maintenance": "Maintenance recommandee",
    "opt.category.boot_block": "Bloque le demarrage",
    "opt.reason.fstrim_missing": "SSD/NVMe detecte mais le TRIM periodique n'est pas active",
    "opt.reason.netm_wait_online": "Retarde le demarrage en attendant que le reseau soit pret",
    "opt.resource.cleanup": "Nettoyage",
    "opt.reason.orphan_symlink": "Lien d'activation casse ({paths}) : le paquet qui l'a cree n'est plus installe",
}
