STRINGS_FR = {
    "main.title": "Services systeme Soplos",
    "tab.services": "Services",
    "tab.logs": "Journaux",
    "table.name": "Nom",
    "table.loaded": "Charge",
    "table.active": "Actif",
    "table.sub": "Sous-etat",
    "table.description": "Description",
    "btn.start": "Demarrer",
    "btn.stop": "Arreter",
    "btn.restart": "Redemarrer",
    "btn.enable": "Activer",
    "btn.disable": "Desactiver",
    "btn.refresh": "Actualiser",
    "details.no_selection": "Selectionnez un service pour voir les details",
    "details.status": "Etat",
    "details.description": "Description",
    "logs.select_service": "Selectionnez un service dans l'onglet Services pour voir ses journaux",
    "logs.no_logs": "Aucun journal disponible pour ce service",
    "status.loading": "Chargement des services...",
    "status.ready": "Pret",
    "status.error": "Erreur lors du chargement des services",
    "confirm.title": "Confirmer",
    "confirm.start": "Demarrer le service {name} ?",
    "confirm.stop": "Arreter le service {name} ?",
    "confirm.restart": "Redemarrer le service {name} ?",
    "confirm.enable": "Activer le service {name} ?",
    "confirm.disable": "Desactiver le service {name} ?",
    "about.comments": "Gestionnaire graphique GTK3 pour les services systemd sous Soplos Linux.",
}
