STRINGS_IT = {
    "main.title": "Servizi di sistema Soplos",
    "tab.services": "Servizi",
    "tab.logs": "Log",
    "table.name": "Nome",
    "table.loaded": "Caricato",
    "table.active": "Attivo",
    "table.sub": "Sottostato",
    "table.description": "Descrizione",
    "btn.start": "Avvia",
    "btn.stop": "Ferma",
    "btn.restart": "Riavvia",
    "btn.enable": "Abilita",
    "btn.disable": "Disabilita",
    "btn.refresh": "Aggiorna",
    "details.no_selection": "Seleziona un servizio per visualizzare i dettagli",
    "details.status": "Stato",
    "details.description": "Descrizione",
    "logs.select_service": "Seleziona un servizio nella scheda Servizi per visualizzarne i log",
    "logs.no_logs": "Nessun log disponibile per questo servizio",
    "status.loading": "Caricamento servizi...",
    "status.ready": "Pronto",
    "status.error": "Errore nel caricamento dei servizi",
    "confirm.title": "Conferma",
    "confirm.start": "Avviare il servizio {name}?",
    "confirm.stop": "Fermare il servizio {name}?",
    "confirm.restart": "Riavviare il servizio {name}?",
    "confirm.enable": "Abilitare il servizio {name}?",
    "confirm.disable": "Disabilitare il servizio {name}?",
    "about.comments": "Gestore grafico GTK3 per i servizi systemd su Soplos Linux.",
    "tab.optimization": "Ottimizzazione",
    "opt.column.service": "Servizio",
    "opt.column.category": "Categoria",
    "opt.column.resource": "Risorsa",
    "opt.column.reason": "Motivo",
    "opt.column.risk": "Rischio",
    "opt.btn.scan": "Scansiona",
    "opt.btn.apply": "Applica selezionati",
    "opt.btn.select_all": "Seleziona tutto",
    "opt.status.scanning": "Analisi del sistema...",
    "opt.status.none_found": "Nessun suggerimento trovato",
    "opt.status.applying": "Applicazione delle modifiche...",
    "opt.category.hardware": "Hardware non presente",
    "opt.category.redundant": "Stack ridondante",
    "opt.category.orphan": "Pacchetto orfano",
    "opt.resource.ram": "RAM",
    "opt.resource.boot": "Avvio",
    "opt.resource.power": "Energia",
    "opt.risk.low": "Basso",
    "opt.risk.medium": "Medio",
    "opt.reason.no_vm": "Nessuna macchina virtuale rilevata",
    "opt.reason.no_bluetooth": "Nessun adattatore Bluetooth rilevato",
    "opt.reason.no_wifi": "Nessun adattatore Wi-Fi rilevato",
    "opt.reason.audio_redundant": "PipeWire e attivo; PulseAudio e ridondante",
    "opt.reason.orphan_pkg": "Il pacchetto {pkg} che lo ha installato non e piu presente",
    "opt.confirm.header": "Verranno applicate le seguenti modifiche:",
    "opt.confirm.summary_disable": "Disabilitare: {count}",
    "opt.confirm.summary_enable": "Abilitare: {count}",
    "opt.confirm.summary_remove": "Rimuovere collegamento orfano: {count}",
    "opt.resource.disk": "Disco",
    "opt.category.maintenance": "Manutenzione consigliata",
    "opt.category.boot_block": "Blocca l'avvio",
    "opt.reason.fstrim_missing": "SSD/NVMe rilevato ma il TRIM periodico non e abilitato",
    "opt.reason.netm_wait_online": "Ritarda l'avvio in attesa che la rete sia pronta",
    "opt.resource.cleanup": "Pulizia",
    "opt.reason.orphan_symlink": "Collegamento di attivazione interrotto ({paths}): il pacchetto che lo ha creato non e piu installato",
}
