STRINGS_IT = {
    "main.title": "Servizi di sistema Soplos",
    "tab.services": "Servizi",
    "tab.logs": "Log",
    "table.name": "Nome",
    "table.loaded": "Caricato",
    "table.active": "Attivo",
    "table.sub": "Sottostato",
    "table.description": "Descrizione",
    "btn.start": "Avvia",
    "btn.stop": "Ferma",
    "btn.restart": "Riavvia",
    "btn.enable": "Abilita",
    "btn.disable": "Disabilita",
    "btn.refresh": "Aggiorna",
    "details.no_selection": "Seleziona un servizio per visualizzare i dettagli",
    "details.status": "Stato",
    "details.description": "Descrizione",
    "logs.select_service": "Seleziona un servizio nella scheda Servizi per visualizzarne i log",
    "logs.no_logs": "Nessun log disponibile per questo servizio",
    "status.loading": "Caricamento servizi...",
    "status.ready": "Pronto",
    "status.error": "Errore nel caricamento dei servizi",
    "confirm.title": "Conferma",
    "confirm.start": "Avviare il servizio {name}?",
    "confirm.stop": "Fermare il servizio {name}?",
    "confirm.restart": "Riavviare il servizio {name}?",
    "confirm.enable": "Abilitare il servizio {name}?",
    "confirm.disable": "Disabilitare il servizio {name}?",
    "about.comments": "Gestore grafico GTK3 per i servizi systemd su Soplos Linux.",
}
