STRINGS_PT = {
    "main.title": "Servicos do sistema Soplos",
    "tab.services": "Servicos",
    "tab.logs": "Registos",
    "table.name": "Nome",
    "table.loaded": "Carregado",
    "table.active": "Ativo",
    "table.sub": "Subestado",
    "table.description": "Descricao",
    "btn.start": "Iniciar",
    "btn.stop": "Parar",
    "btn.restart": "Reiniciar",
    "btn.enable": "Ativar",
    "btn.disable": "Desativar",
    "btn.refresh": "Atualizar",
    "details.no_selection": "Selecione um servico para ver os detalhes",
    "details.status": "Estado",
    "details.description": "Descricao",
    "logs.select_service": "Selecione um servico no separador Servicos para ver os seus registos",
    "logs.no_logs": "Sem registos disponiveis para este servico",
    "status.loading": "A carregar servicos...",
    "status.ready": "Pronto",
    "status.error": "Erro ao carregar os servicos",
    "confirm.title": "Confirmar",
    "confirm.start": "Iniciar o servico {name}?",
    "confirm.stop": "Parar o servico {name}?",
    "confirm.restart": "Reiniciar o servico {name}?",
    "confirm.enable": "Ativar o servico {name}?",
    "confirm.disable": "Desativar o servico {name}?",
    "about.comments": "Gestor grafico GTK3 para servicos systemd no Soplos Linux.",
    "tab.optimization": "Otimizacao",
    "opt.column.service": "Servico",
    "opt.column.category": "Categoria",
    "opt.column.resource": "Recurso",
    "opt.column.reason": "Motivo",
    "opt.column.risk": "Risco",
    "opt.btn.scan": "Analisar",
    "opt.btn.apply": "Aplicar selecionados",
    "opt.btn.select_all": "Selecionar tudo",
    "opt.status.scanning": "A analisar o sistema...",
    "opt.status.none_found": "Nenhuma sugestao encontrada",
    "opt.status.applying": "A aplicar alteracoes...",
    "opt.category.hardware": "Hardware nao presente",
    "opt.category.redundant": "Stack redundante",
    "opt.category.orphan": "Pacote orfao",
    "opt.resource.ram": "RAM",
    "opt.resource.boot": "Arranque",
    "opt.resource.power": "Energia",
    "opt.risk.low": "Baixo",
    "opt.risk.medium": "Medio",
    "opt.reason.no_vm": "Nenhuma maquina virtual detetada",
    "opt.reason.no_bluetooth": "Nenhum adaptador Bluetooth detetado",
    "opt.reason.no_wifi": "Nenhum adaptador Wi-Fi detetado",
    "opt.reason.audio_redundant": "PipeWire esta ativo; PulseAudio e redundante",
    "opt.reason.orphan_pkg": "O pacote {pkg} que o instalou ja nao esta presente",
    "opt.confirm.header": "Vao ser aplicadas as seguintes alteracoes:",
    "opt.confirm.summary_disable": "Desativar: {count}",
    "opt.confirm.summary_enable": "Ativar: {count}",
    "opt.confirm.summary_remove": "Remover ligacao orfa: {count}",
    "opt.resource.disk": "Disco",
    "opt.category.maintenance": "Manutencao recomendada",
    "opt.category.boot_block": "Bloqueia o arranque",
    "opt.reason.fstrim_missing": "SSD/NVMe detetado mas o TRIM periodico nao esta ativado",
    "opt.reason.netm_wait_online": "Atrasa o arranque a espera que a rede esteja pronta",
    "opt.resource.cleanup": "Limpeza",
    "opt.reason.orphan_symlink": "Ligacao de ativacao quebrada ({paths}): o pacote que a criou ja nao esta instalado",
}
