STRINGS_PT = {
    "main.title": "Servicos do sistema Soplos",
    "tab.services": "Servicos",
    "tab.logs": "Registos",
    "table.name": "Nome",
    "table.loaded": "Carregado",
    "table.active": "Ativo",
    "table.sub": "Subestado",
    "table.description": "Descricao",
    "btn.start": "Iniciar",
    "btn.stop": "Parar",
    "btn.restart": "Reiniciar",
    "btn.enable": "Ativar",
    "btn.disable": "Desativar",
    "btn.refresh": "Atualizar",
    "details.no_selection": "Selecione um servico para ver os detalhes",
    "details.status": "Estado",
    "details.description": "Descricao",
    "logs.select_service": "Selecione um servico no separador Servicos para ver os seus registos",
    "logs.no_logs": "Sem registos disponiveis para este servico",
    "status.loading": "A carregar servicos...",
    "status.ready": "Pronto",
    "status.error": "Erro ao carregar os servicos",
    "confirm.title": "Confirmar",
    "confirm.start": "Iniciar o servico {name}?",
    "confirm.stop": "Parar o servico {name}?",
    "confirm.restart": "Reiniciar o servico {name}?",
    "confirm.enable": "Ativar o servico {name}?",
    "confirm.disable": "Desativar o servico {name}?",
    "about.comments": "Gestor grafico GTK3 para servicos systemd no Soplos Linux.",
}
