STRINGS_RO = {
    "main.title": "Servicii de sistem Soplos",
    "tab.services": "Servicii",
    "tab.logs": "Jurnale",
    "table.name": "Nume",
    "table.loaded": "Incarcat",
    "table.active": "Activ",
    "table.sub": "Substare",
    "table.description": "Descriere",
    "btn.start": "Pornire",
    "btn.stop": "Oprire",
    "btn.restart": "Repornire",
    "btn.enable": "Activare",
    "btn.disable": "Dezactivare",
    "btn.refresh": "Actualizare",
    "details.no_selection": "Selectati un serviciu pentru a vedea detaliile",
    "details.status": "Stare",
    "details.description": "Descriere",
    "logs.select_service": "Selectati un serviciu din fila Servicii pentru a-i vedea jurnalele",
    "logs.no_logs": "Nu sunt disponibile jurnale pentru acest serviciu",
    "status.loading": "Se incarca serviciile...",
    "status.ready": "Gata",
    "status.error": "Eroare la incarcarea serviciilor",
    "confirm.title": "Confirmare",
    "confirm.start": "Porniti serviciul {name}?",
    "confirm.stop": "Opriti serviciul {name}?",
    "confirm.restart": "Reporniti serviciul {name}?",
    "confirm.enable": "Activati serviciul {name}?",
    "confirm.disable": "Dezactivati serviciul {name}?",
    "about.comments": "Manager grafic GTK3 pentru serviciile systemd pe Soplos Linux.",
    "tab.optimization": "Optimizare",
    "opt.column.service": "Serviciu",
    "opt.column.category": "Categorie",
    "opt.column.resource": "Resursa",
    "opt.column.reason": "Motiv",
    "opt.column.risk": "Risc",
    "opt.btn.scan": "Scanare",
    "opt.btn.apply": "Aplicare selectie",
    "opt.btn.select_all": "Selectare totala",
    "opt.status.scanning": "Se scaneaza sistemul...",
    "opt.status.none_found": "Nu s-au gasit sugestii",
    "opt.status.applying": "Se aplica modificarile...",
    "opt.category.hardware": "Hardware absent",
    "opt.category.redundant": "Stiva redundanta",
    "opt.category.orphan": "Pachet orfan",
    "opt.resource.ram": "RAM",
    "opt.resource.boot": "Pornire",
    "opt.resource.power": "Energie",
    "opt.risk.low": "Scazut",
    "opt.risk.medium": "Mediu",
    "opt.reason.no_vm": "Nu s-a detectat nicio masina virtuala",
    "opt.reason.no_bluetooth": "Nu s-a detectat niciun adaptor Bluetooth",
    "opt.reason.no_wifi": "Nu s-a detectat niciun adaptor Wi-Fi",
    "opt.reason.audio_redundant": "PipeWire este activ; PulseAudio este redundant",
    "opt.reason.orphan_pkg": "Pachetul {pkg} care l-a instalat nu mai este prezent",
    "opt.confirm.header": "Vor fi aplicate urmatoarele modificari:",
    "opt.confirm.summary_disable": "Dezactivare: {count}",
    "opt.confirm.summary_enable": "Activare: {count}",
    "opt.confirm.summary_remove": "Eliminare legatura orfana: {count}",
    "opt.resource.disk": "Disc",
    "opt.category.maintenance": "Intretinere recomandata",
    "opt.category.boot_block": "Blocheaza pornirea",
    "opt.reason.fstrim_missing": "SSD/NVMe detectat, dar TRIM periodic nu este activat",
    "opt.reason.netm_wait_online": "Intarzie pornirea asteptand ca reteaua sa fie gata",
    "opt.resource.cleanup": "Curatare",
    "opt.reason.orphan_symlink": "Legatura de activare defecta ({paths}): pachetul care a creat-o nu mai este instalat",
}
