STRINGS_RO = {
    "main.title": "Servicii de sistem Soplos",
    "tab.services": "Servicii",
    "tab.logs": "Jurnale",
    "table.name": "Nume",
    "table.loaded": "Incarcat",
    "table.active": "Activ",
    "table.sub": "Substare",
    "table.description": "Descriere",
    "btn.start": "Pornire",
    "btn.stop": "Oprire",
    "btn.restart": "Repornire",
    "btn.enable": "Activare",
    "btn.disable": "Dezactivare",
    "btn.refresh": "Actualizare",
    "details.no_selection": "Selectati un serviciu pentru a vedea detaliile",
    "details.status": "Stare",
    "details.description": "Descriere",
    "logs.select_service": "Selectati un serviciu din fila Servicii pentru a-i vedea jurnalele",
    "logs.no_logs": "Nu sunt disponibile jurnale pentru acest serviciu",
    "status.loading": "Se incarca serviciile...",
    "status.ready": "Gata",
    "status.error": "Eroare la incarcarea serviciilor",
    "confirm.title": "Confirmare",
    "confirm.start": "Porniti serviciul {name}?",
    "confirm.stop": "Opriti serviciul {name}?",
    "confirm.restart": "Reporniti serviciul {name}?",
    "confirm.enable": "Activati serviciul {name}?",
    "confirm.disable": "Dezactivati serviciul {name}?",
    "about.comments": "Manager grafic GTK3 pentru serviciile systemd pe Soplos Linux.",
}
