STRINGS_RU = {
    "main.title": "Системные службы Soplos",
    "tab.services": "Службы",
    "tab.logs": "Журналы",
    "table.name": "Имя",
    "table.loaded": "Загружено",
    "table.active": "Активно",
    "table.sub": "Подстатус",
    "table.description": "Описание",
    "btn.start": "Запустить",
    "btn.stop": "Остановить",
    "btn.restart": "Перезапустить",
    "btn.enable": "Включить",
    "btn.disable": "Отключить",
    "btn.refresh": "Обновить",
    "details.no_selection": "Выберите службу для просмотра подробностей",
    "details.status": "Состояние",
    "details.description": "Описание",
    "logs.select_service": "Выберите службу на вкладке Службы для просмотра журналов",
    "logs.no_logs": "Для этой службы журналы недоступны",
    "status.loading": "Загрузка служб...",
    "status.ready": "Готово",
    "status.error": "Ошибка при загрузке служб",
    "confirm.title": "Подтверждение",
    "confirm.start": "Запустить службу {name}?",
    "confirm.stop": "Остановить службу {name}?",
    "confirm.restart": "Перезапустить службу {name}?",
    "confirm.enable": "Включить службу {name}?",
    "confirm.disable": "Отключить службу {name}?",
    "about.comments": "Графический менеджер GTK3 для служб systemd в Soplos Linux.",
    "tab.optimization": "Оптимизация",
    "opt.column.service": "Служба",
    "opt.column.category": "Категория",
    "opt.column.resource": "Ресурс",
    "opt.column.reason": "Причина",
    "opt.column.risk": "Риск",
    "opt.btn.scan": "Сканировать",
    "opt.btn.apply": "Применить выбранное",
    "opt.btn.select_all": "Выбрать все",
    "opt.status.scanning": "Сканирование системы...",
    "opt.status.none_found": "Предложений не найдено",
    "opt.status.applying": "Применение изменений...",
    "opt.category.hardware": "Оборудование отсутствует",
    "opt.category.redundant": "Избыточный стек",
    "opt.category.orphan": "Осиротевший пакет",
    "opt.resource.ram": "ОЗУ",
    "opt.resource.boot": "Загрузка",
    "opt.resource.power": "Энергия",
    "opt.risk.low": "Низкий",
    "opt.risk.medium": "Средний",
    "opt.reason.no_vm": "Виртуальная машина не обнаружена",
    "opt.reason.no_bluetooth": "Адаптер Bluetooth не обнаружен",
    "opt.reason.no_wifi": "Адаптер Wi-Fi не обнаружен",
    "opt.reason.audio_redundant": "PipeWire активен; PulseAudio избыточен",
    "opt.reason.orphan_pkg": "Пакет {pkg}, установивший службу, больше не установлен",
    "opt.confirm.header": "Будут применены следующие изменения:",
    "opt.confirm.summary_disable": "Отключить: {count}",
    "opt.confirm.summary_enable": "Включить: {count}",
    "opt.confirm.summary_remove": "Удалить осиротевшую ссылку: {count}",
    "opt.resource.disk": "Диск",
    "opt.category.maintenance": "Рекомендуемое обслуживание",
    "opt.category.boot_block": "Блокирует загрузку",
    "opt.reason.fstrim_missing": "Обнаружен SSD/NVMe, но периодический TRIM не включен",
    "opt.reason.netm_wait_online": "Задерживает загрузку в ожидании готовности сети",
    "opt.resource.cleanup": "Очистка",
    "opt.reason.orphan_symlink": "Битая ссылка активации ({paths}): пакет, который её создал, больше не установлен",
}
