STRINGS_RU = {
    "main.title": "Системные службы Soplos",
    "tab.services": "Службы",
    "tab.logs": "Журналы",
    "table.name": "Имя",
    "table.loaded": "Загружено",
    "table.active": "Активно",
    "table.sub": "Подстатус",
    "table.description": "Описание",
    "btn.start": "Запустить",
    "btn.stop": "Остановить",
    "btn.restart": "Перезапустить",
    "btn.enable": "Включить",
    "btn.disable": "Отключить",
    "btn.refresh": "Обновить",
    "details.no_selection": "Выберите службу для просмотра подробностей",
    "details.status": "Состояние",
    "details.description": "Описание",
    "logs.select_service": "Выберите службу на вкладке Службы для просмотра журналов",
    "logs.no_logs": "Для этой службы журналы недоступны",
    "status.loading": "Загрузка служб...",
    "status.ready": "Готово",
    "status.error": "Ошибка при загрузке служб",
    "confirm.title": "Подтверждение",
    "confirm.start": "Запустить службу {name}?",
    "confirm.stop": "Остановить службу {name}?",
    "confirm.restart": "Перезапустить службу {name}?",
    "confirm.enable": "Включить службу {name}?",
    "confirm.disable": "Отключить службу {name}?",
    "about.comments": "Графический менеджер GTK3 для служб systemd в Soplos Linux.",
}
